ALTER TABLE accounts ADD Email varchar(255) DEFAULT "NO_ADDRESS" NOT NULL;
ALTER TABLE accounts ADD Discord varchar(255) DEFAULT "NO_DISCORD";
ALTER TABLE accounts ADD Subscribed TINYINT(1) DEFAULT 0 NOT NULL;